version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  test-and-build:
    working_directory: ~/3id-connect
    docker:
      - image: mcr.microsoft.com/playwright:focal
        environment:
          NODE_ENV: development
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}

      - run:
          name: install dependencies
          command: |
            apt-get update && apt-get install -y --no-install-recommends python make gcc g++
            npm i -g codecov node-gyp
            npm ci

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: npm test

      - run:
          name: build
          command: npm run build

      # - run:
      #     name: code-coverage
      #     command: bash <(curl -s https://codecov.io/bash)

      - persist_to_workspace:
          root: .
          paths:
            - public

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deploy-dev:
    working_directory: ~/3id-connect
    docker:
      - image: 'circleci/python:3.8'
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: '--acl public-read --cache 604800'
          from: public
          overwrite: true
          to: 's3://3id-connect-dev-ceramic'
      - run:
          name: 'Invalidate CloudFront Cache'
          command: aws cloudfront create-invalidation --distribution-id E1PKS2J8XTFTYN --paths /*

  deploy-prod:
    working_directory: ~/3id-connect
    docker:
      - image: 'circleci/python:3.8'
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: '--acl public-read --cache 604800'
          from: public
          overwrite: true
          to: 's3://3id-connect-prod-ceramic'
      - run:
          name: 'Invalidate CloudFront Cache'
          command: aws cloudfront create-invalidation --distribution-id E1JN8AUJY96OQ9 --paths /*

workflows:
  build-deploy:
    jobs:
      - test-and-build
      - deploy-dev:
          requires:
            - test-and-build
          filters:
            branches:
              only: develop
      - deploy-prod:
          requires:
            - test-and-build
          filters:
            branches:
              only: master
